version: "3.5"

services:
  vpn:
    container_name: NordVPN
    image: bubuntux/nordvpn:latest
    restart: unless-stopped
    hostname: nordvpn
    env_file: .env
    cap_add:
      - NET_ADMIN    # Required
    devices:
      - /dev/net/tun
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=${VPN_USER}
      - PASS=${VPN_PASSWORD}
      - CONNECT=${VPN_COUNTRY}
      - TECHNOLOGY=NordLynx
      - NETWORK=${NETWORK}
    ports:
      - ${VPN_PORT}:6881
      - ${VPN_PORT}:6881/udp
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
      - ${RADARR_PORT}:7878
      - ${SONARR_PORT}:8989
      - ${LIDARR_PORT}:8686
      - ${BAZARR_PORT}:6767
      - ${XTEVE_PORT}:34400
      - ${PROWLARR_PORT}:9696
      - ${FLARESOLVERR_PORT}:8191
      - ${NZBGET_PORT}:6789
    networks:
      NordVPN:
        ipv4_address: 10.6.0.5
        aliases:
          - nordvpn

  qbittorrent:
    container_name: qBittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn
    environment:
      - WEBUI_PORT=${QBITTORRENT_PORT}
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
    volumes:
      - ${ROOT}/qbittorrent:/config
      - ${DOWNLOAD_ROOT}:/downloads
    depends_on:
      - vpn

  prowlarr:
    container_name: Prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/prowlarr/config:/config # config files
    depends_on:
      - vpn

  sonarr:
    container_name: Sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/sonarr/config/:/config # config files
      - ${MEDIA_ROOT}/TV:/tv # tv shows folder
      - ${DOWNLOAD_ROOT}/:/downloads # download folder
    depends_on:
      - vpn
      - prowlarr

  radarr:
    container_name: Radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/radarr/config/:/config # config files
      - ${MEDIA_ROOT}/Movies:/movies # movies folder
      - ${DOWNLOAD_ROOT}/:/downloads # download folder
    depends_on:
      - vpn
      - prowlarr

  lidarr:
    container_name: Lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/lidarr/config/:/config # config files
      - ${MEDIA_ROOT}/Music:/music # movies folder
      - ${DOWNLOAD_ROOT}/:/downloads # download folder
    depends_on:
      - vpn
      - prowlarr

  bazarr:
    container_name: Bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/bazarr/config/:/config # config files
      - ${MEDIA_ROOT}/Movies:/movies # movies folder, same as Radarr
      - ${MEDIA_ROOT}/TV:/tv # tv shows folder, same as Sonarr
    depends_on:
      - vpn
      
  xteve:
    container_name: xTeVe
    image: 'dnsforge/xteve'
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/xteve:/home/xteve/conf
      - ${ROOT}/xteve/temp:/tmp/xteve
      - ${ROOT}/xteve/log:/var/log
    depends_on:
      - vpn
      
  flaresolverr:
    container_name: FlareSolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ} # timezone, defined in .env
    depends_on:
      - vpn
      
  nzbget:
    container_name: NZBget
    image: lscr.io/linuxserver/nzbget:latest
    restart: unless-stopped
    env_file: .env
    network_mode: service:vpn # Run on the VPN Network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/nzbget:/config
      - ${DOWNLOAD_ROOT}:/downloads #optional
    depends_on:
      - vpn

networks:
  NordVPN:
    ipam:
      config:
        - subnet: 10.6.0.0/16
